# Generated by Django 5.2.8 on 2025-11-24 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('info', 'Info'), ('join', 'Join'), ('support', 'Support')], help_text='Which section this belongs to', max_length=20, unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('body_en', models.TextField()),
                ('title_cy', models.CharField(max_length=255)),
                ('body_cy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('past', 'Past'), ('present', 'Present'), ('future', 'Future')], max_length=10)),
                ('published_at', models.DateField(default=datetime.date.today)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('link_en', models.URLField(blank=True)),
                ('title_cy', models.CharField(max_length=255)),
                ('description_cy', models.TextField()),
                ('link_cy', models.URLField(blank=True)),
                ('poster_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('leader1_name', models.CharField(blank=True, max_length=200)),
                ('leader1_role', models.CharField(blank=True, max_length=200)),
                ('leader1_description', models.TextField(blank=True)),
                ('leader1_photo', models.ImageField(blank=True, null=True, upload_to='leaders/')),
                ('leader2_name', models.CharField(blank=True, max_length=200)),
                ('leader2_role', models.CharField(blank=True, max_length=200)),
                ('leader2_description', models.TextField(blank=True)),
                ('leader2_photo', models.ImageField(blank=True, null=True, upload_to='leaders/')),
                ('leader3_name', models.CharField(blank=True, max_length=200)),
                ('leader3_role', models.CharField(blank=True, max_length=200)),
                ('leader3_description', models.TextField(blank=True)),
                ('leader3_photo', models.ImageField(blank=True, null=True, upload_to='leaders/')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('manual', 'Manual / Guide'), ('manifesto', 'Manifesto'), ('policy', 'Policy / Framework'), ('other', 'Other')], default='other', max_length=20)),
                ('published_at', models.DateField(default=datetime.date.today)),
                ('title_en', models.CharField(max_length=255)),
                ('description_en', models.TextField(blank=True)),
                ('title_cy', models.CharField(max_length=255)),
                ('description_cy', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resources/')),
                ('link', models.URLField(blank=True, help_text='Optional external link')),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
